name: 'Build'

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  test-cmake-minimum:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 3.17.2
      - name: Run CMake
        working-directory: ./build
        run: cmake ../
      - name: Build
        run: cmake --build build/
      - name: Test
        run: cd build && ctest --output-on-failure
